---
- name: Create inventory and save vars
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    inventory_name: "My Inventory"
    group_name: "My Group"
    host_name: "my_dynamic_host"

  tasks:
    - name: Create dynamic host
      add_host:
        name: "{{ host_name }}"
        ansible_host: 13.229.89.61
        ansible_connection: local
        
    - name: Create inventory
      tower_inventory:
        #tower_config_file: var/lib/awx/projects/tower-cli.cfg
        name: "{{ inventory_name }}"   
        state: present
        organization: Default

    - name: Create group
      tower_group:
        #tower_config_file: var/lib/awx/projects/tower-cli.cfg
        inventory: "{{ inventory_name }}"
        name: "{{ group_name }}"
        state: present
        organization: Default

    - name: Add host to group
      tower_host:
       # tower_config_file: /var/lib/awx/projects/tower-cli.cfg
        inventory: "{{ inventory_name }}"
        name: "{{ host_name }}"
        #groups: "{{ group_name }}"
        variables: "{{ company }}"
        state: present
