---
- name: Create Ansible Tower Inventory
  hosts: localhost
  gather_facts: no
  vars:
    awx_base_url: "https://tower.example.com"  # Replace with your AWX URL
    awx_username: "your_username"
    awx_password: "your_password"
    organization_id: Default
    inventory_name: "My_New_Inventory"
  tasks:
    - name: Create Inventory
      uri:
        url: "{{ awx_base_url }}/api/v2/inventories/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        body_format: json
        body: '{"name": "{{ inventory_name }}", "organization": {{ organization_id }}}'
        status_code: 201
        validate_certs: no 
      register: create_inventory_response

    - name: Display API Response
      debug:
        var: create_inventory_response.json
